apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: &app descheduler
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
