---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis-operator
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: spotahome-redis-operator-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 7
    crds: Create
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
