apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_MOSQUITTO_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            allow_anonymous false
            persistence true
            persistence_location /mosquitto/data
            password_file /mosquitto/config/mqttpassword
            connection_messages false
    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      data:
        enabled: true
        existingClaim: mosquitto-data
        mountPath: /mosquitto/data
      passwordfile:
        enabled: true
        type: secret
        name: *app
        mountPath: /mosquitto/config/mqttpassword
        subPath: mqttpassword
        readOnly: true
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 15m
        memory: 105Mi
      limits:
        memory: 105Mi
