apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname nzbhydra2
  namespace: media
spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname
      version: "10.4.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    podLabels:
      app: *appname
    podSecurityContext:
      fsGroup: 568

    image:
      repository: ghcr.io/k8s-at-home/nzbhydra2
      tag: v4.6.1
        #tag: v3.14.2
      pullPolicy: IfNotPresent
    
    env:
      TZ: ${TIMEZONE}
    
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 5076
    
    persistence:
      config:
        enabled: true
        existingClaim: nzbhydra2-config-volume
      omoikane:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/omoikane
        mountPath: /omoikane
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/backups
        mountPath: /config/backup

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
          hajimari.io/appName: "NZBHydra"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "nzbhydra.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *uri
            secretName: *uri
