# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname privategpt
  namespace: &namespace home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: ghcr.io/imartinez/privategpt
              tag: sha-6583dc8
            env:
              TZ: ${TIMEZONE}
              PERSIST_DIRECTORY: db
              MODEL_TYPE: OpenAI
              EMBEDDINGS_MODEL_NAME: text-embedding-ada-002
              MODEL_N_CTX: 1000
              OPENAI_API_BASE: http://localai.home.svc.cluster.local/v1

            resources:
              requests:
                cpu: 15m
                memory: 94M
        statefulset:
          volumeClaimTemplates:
            - name: local-data
              accessMode: ReadWriteMany
              size: 5Gi
              storageClass: longhorn
              labels:
                snapshot.home.arpa/enabled: 'true'
              globalMounts:
                - path: /home/worker/app/local_data
    service:
      main:
        ports:
          http:
            port: 8080
        primary: true
        controller: main
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          hajimari.io/enable: 'true'
          hajimari.io/icon: baby-bottle-outline
          hajimari.io/info: ChatGPT
          hajimari.io/group: &namespace home
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri chat.${SECRET_DEV_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *uri
            secretName: *uri
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: "OnRootMismatch"
