---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m

  values:
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.25.2

    strategy:
      type: Recreate

    env:
      DATA_FOLDER: "config"
      ICON_CACHE_FOLDER: "config/icon_cache"
      ATTACHMENTS_FOLDER: "config/attachments"
      SENDS_FOLDER: "config/sends"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      ROCKET_PORT: 8080
      DOMAIN: https://vault.${SECRET_DEV_DOMAIN_MGO}
    envFrom:
      - secretRef:
          name: *app

    service:
      main:
        primary: true
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
        type: LoadBalancer
        externalTrafficPolicy: Local
        
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-authelia@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          hajimari.io/appName: "vaultwarden"
          # external-dns/is-public: "true"
          # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DEV_DOMAIN}"
        hosts:
        - host: &uri "vault.${SECRET_DEV_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              port: 8080
          - path: /notifications/hub
            pathType: Prefix
            service:
              port: 3012
          - path: /notifications/hub/negotiate
            pathType: Prefix
            service:
              port: 8080
        tls:
        - hosts:
          - *uri
          secretName: *uri
      admin:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-authelia@kubernetescrd"
        hosts:
        - host: *uri
          paths:
          - path: /admin
            pathType: Prefix
            service:
              port: 8080
        - host: *uri2
          paths:
          - path: /admin
            pathType: Prefix
            service:
              port: 8080
        tls:
        - hosts:
          - *uri
          - *uri2
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config-volume

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 2000Mi

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
