apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app vaultwarden
  app.kubernetes.io/instance: *app
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - secret.sops.yaml
    #- volsync.yaml
