---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/dpage/pgadmin4
      tag: latest
      pullPolicy: Always
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - configMapRef:
          name: *app
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    service:
      main:
        ports:
          http:
            port: &port 80
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "database-cog-outline"
          hajimari.io/appName: "PG Admin 4"
          hajimari.io/group: "Utilities"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "pgadmin.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
    probes:
      liveness: &probes
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /
            port: *port
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 5050
      runAsGroup: 5050
      fsGroup: 5050
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: pgadmin-config
        mountPath: "/var/lib/pgadmin"
      server-json:
        enabled: true
        type: configMap
        name: servers-json
        subPath: servers.json
        mountPath: /pgadmin4/servers.json
