apiVersion: v1
kind: Secret
metadata:
    name: gamevault
    namespace: home
stringData:
    DB_SYSTEM: ENC[AES256_GCM,data:PyDnum4taPFrLw==,iv:YYRgflTkchN1ikjoPrPLxLDbWo6+RmZ4aRdQ/VwkN5s=,tag:O/SF9az90wC3Eb6dm2ZK6w==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:8yVoqsJxsmyL,iv:RA4FOFg/GhopTiUcRsqrdHdZs9q1F0fh5wYsa8i1jtw=,tag:HZR33dXX6bQ4xz2/IjKNkQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:gOCaR6cQnN06,iv:PKCbFYXOoQqNNr0SbfT7wEmbhSYQkW+bnLRCWZ7z/bs=,tag:pPkr/Hwv/0yoYND6+KEUyQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:G6xbFtmBvl44NGt3uKuZKw7xeT8OFp7RvyM+W7dJf8hEM8ODE62+dpAOKXRhaHoOza+rLtLiOzTaNmx2XJ3pRQ==,iv:4li49xSkIE4VG94qJZiERVsawKiu8G9VlopfOGpU2tU=,tag:y/zBgdvEN7DkMVd+Kl/QXw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:xtuM5STAqnNxrYROjyY7lMF9z5jR4yK6EPP4V0ql6qfUf9N81Pcb9A==,iv:rjfS4P/S/bx28Z316oW6/uvLvDLJxtsgzdxRdE3/6eM=,tag:GElkTVzzWdyspJjIMMyqoA==,type:str]
    SERVER_ADMIN_USERNAME: ENC[AES256_GCM,data:S3GTezk=,iv:Joj0wBaYJKDAjvzvd6wfBjbK+DRYW2OxwH0KwmjHfZk=,tag:hU1PEP5D+xsRs/wQmDsuEA==,type:str]
    RAWG_API_KEY: ENC[AES256_GCM,data:ubRHLh7ig3RBgbE+UGgeYhn8Cz+eaAVbKCZ8OTLfQtw=,iv:YjPIPmXuyMyaD5EwzLKJQr51hJaT/ENP25xX6D6TKg0=,tag:E5yZUG3W8pmMAwLdwu5Hfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxek1OLzRqLzZLZnM4cXRR
            QkZlTUVJN1Robk9paTVmYWpKTnBJZ21JRWljCk00cDd5dHFiM1F6a0g2S1o1VEl4
            UkxnalFKMjZwNjlQZnFaOVRyY0ZOVjQKLS0tIGV2YXd2b2sxdTJOcDhRSWw5c05q
            ajdTT3plSCtkR21TWXNkUVEzTkJpemcK2gAUwRIoEm5U52iZ8x1FjwUEA7cBREnl
            DBalwKuQPQhRoMx+M4e5Vvf+3vyWrrmlm/549UpRfcGVNwr8dOgH5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T17:51:46Z"
    mac: ENC[AES256_GCM,data:zBo5O4mVUSVn4Mt1lOv4XxZi7AdGnlWPnglpw46HZ8zislmHx8ima5l8us4UOsLSau9UxsgHkxKlXbI8+IOvO1Xhzjkisue9bFu1Ro8b1qyy2oqPICZIQggVq8R51/6EB5gv9D5mJDwvFwM996xQjL7+YtQlEHCLBbIti8r0OVE=,iv:N94Z30rrWMZwy/TPu4z7vaDSoWtzyh9QXw6Rs9uCXsA=,tag:cSnyNwRR7gLiV6u5f7U64Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
