apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
spec:
  accessModes:
      - ReadWriteMany
  storageClassName: longhorn
  resources:
      requests:
          storage: 128Mi

