---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/minio/minio
      tag: RELEASE.2023-06-02T23-17-26Z
      pullPolicy: Always
    env:
      TZ: "America/Los_Angeles"
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      MINIO_PROMETHEUS_JOB_ID: minio
      MINIO_BROWSER_REDIRECT_URL: "https://minio.${SECRET_DEV_DOMAIN}"
      MINIO_SERVER_URL: "https://s3.${SECRET_DEV_DOMAIN}"
    envFrom:
      - secretRef:
          name: *app
    args: ["server", "/data", "--console-address", ":9001"]
    service:
      main:
        enabled: true
        ports:
          http:
            port: &port-console 9001
          api:
            enabled: true
            port: &port-api 9000
#    serviceMonitor:
#      main:
#        enabled: true
#        endpoints:
#          - port: api
#            scheme: http
#            path: /minio/v2/metrics/cluster
#            interval: 1m
#            scrapeTimeout: 10s
#            bearerTokenSecret:
#              name: minio-secret
#              key: MINIO_PROMETHEUS_TOKEN
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-upload"
          hajimari.io/group: "Storage"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia-minio@kubernetescrd
        hosts:
          - host: &host-console "{{ .Release.Name }}.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-console
          - host: &host-api "s3.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port-api
        tls:
          - hosts:
              - *host-console
              - *host-api
            secretName: *host-api
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: minio-nfs
        mountPath: /data
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
