apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app adguard
  app.kubernetes.io/instance: *app
resources:
  - config-pvc.yaml
  - helm-release.yaml
