apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app nextcloud
  namespace: storage
spec:
  endpoints:
  - interval: 1m
    path: /
    port: metrics
    scrapeTimeout: 10s
  jobLabel: ""
  namespaceSelector:
    any: true
    #    matchNames:
    #    - storage
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: *app
      app.kubernetes.io/name: *app
