---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app cloudflare-ddns
  app.kubernetes.io/instance: *app
resources:
  - cron-job.yaml
    #  - secret.sops.yaml
namespace: networking
configMapGenerator:
  - name: cloudflare-ddns
    files:
      - cloudflare-ddns.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
