apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - helm-release.yaml
  - github.com/spotahome/redis-operator/manifests/kustomize/overlays/full
    #  - secret.sops.yaml
configMapGenerator:
  - name: redis-operator-dashboard
    files:
      - redis-operator-dashboard.json=https://raw.githubusercontent.com/spotahome/redis-operator/master/example/grafana-dashboard/redisfailover-health.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
