apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plex-config-volume
    labels:
      app: plex
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 50Gi

