apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname nzbhydra2
  namespace: media
spec:
  releaseName: *appname
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 4
  values:
    podLabels:
      app: *appname
    podSecurityContext:
      fsGroup: 568

    image:
      repository: lscr.io/linuxserver/nzbhydra2
      tag: v4.7.6-ls82
      pullPolicy: Always
    
    env:
      TZ: ${TIMEZONE}
    
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 5076
    
    persistence:
      config:
        enabled: true
        existingClaim: nzbhydra2-config-volume
      omoikane:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/omoikane
        mountPath: /omoikane
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/backups/nzbhydra2
        mountPath: /config/backup

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
          hajimari.io/appName: "NZBHydra"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "nzbhydra.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *uri
            secretName: *uri
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
