---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app invidious-server
  namespace: media
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        env:
          - name: POSTGRES_HOST
            value: defaultpg-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: *app
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *app
                key: USERNAME
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *app 
                key: PASSWORD
