apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: utilities
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: "6.3.6"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  test:
    enable: false
  interval: 5m
  values:
    image:
      pullPolicy: Always
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "information-outline"
        hajimari.io/group: "Utilities"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
      hosts:
        - host: &uri "podinfo.${SECRET_DEV_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - *uri
          secretName: *uri

    nodeSelector:
      node-role.kubernetes.io/worker: "true"
