---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.5.2
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      install: true
    replicaCount: 3
    grafana:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m
    backgroundController:
      serviceMonitor:
        enabled: true
        interval: 1m
    cleanupController:
      serviceMonitor:
        enabled: true
        interval: 1m
    reportsController:
      serviceMonitor:
        enabled: true
        interval: 1m
