---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: multus
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2

    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.3.0

      paths:
        config: /var/lib/rancher/k3s/agent/etc/cni/net.d/
        bin: /var/lib/rancher/k3s/data/ad774f9b85e0ed18b900fb55939212cdc63b13cfcac93670a6fa7d4ff913d746/bin/

      version: "0.3.1"

