---
# yaml-language-server: $schema=http://kubernetes-schemas.local.lan:8080/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nvidia-gpu-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-node-feature-discovery
  path: ./cluster/staging/apps/kube-system/nvidia-gpu-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
