apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:SJFpu5n+nbBuuW3/4nHajKKJtYqId0/8sCSoUPNHkY6Sk6ko,iv:rmbAGVj+MzttDnAKuHwXC7ukGMV7mpu+lt5B8JJ+TXY=,tag:VJXeeErgZ78TSx/W1K13Hw==,type:str]
    port: ENC[AES256_GCM,data:s/22aw==,iv:90UYmHs6eslxwSJbijHXzLOJq307XXvuo/cctUg5jY0=,tag:aWX5nqJU+yg84yK9+iD/VA==,type:str]
    password: ENC[AES256_GCM,data:d/aQXl4fKKcSf3wZE5lqewSMEvWFkxjL,iv:KkYHgCKyIPpcxE/Li2mKZEw+vzvA7+MNaPoCmyk8HhA=,tag:SsoAO71L/Sgru6Isl3VP3A==,type:str]
    connstr: ENC[AES256_GCM,data:yI+Iv7YHtAs8bTiQ7u49d+7ZbtvelAeJnC6lojOyCDax6pITSl9M2eIbLl2wWB3jqxq2Nc6oywLHvYkwP5TpLHy50Q==,iv:ynS9yiudjbtgMGh8MfhG2tzv/cveHg7VvJA+zwrKow4=,tag:uBNr51VUInbjDU0gxBKV/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUCs2SjZPajJLcmpmZUZl
            YUFRY1ZFeHRhSE9sNkRPdTlOSVRxdU83eFZVCkN3dnNNT2UyOWQxSktzbkRKWE1V
            V01CMXdDRlJoeDJMYmhpMGVWQ21qR00KLS0tIGs0NGJzNkRPU3hXakVIZDRiSU43
            aEN5THdWYUVlOE1ZUGpXTXVpdmkrWEUK1hwZdsYE+Ai1zo+xPHXIVD49ORD/GDtj
            4UHTYYoomQAyhMisymonZsrq8jetnsEjVMNRYqH504mGaQHwf34wDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-13T21:12:17Z"
    mac: ENC[AES256_GCM,data:jors92lyB6jnQnC0oOlb0TPI2SAo1S05m56WK7c0PUJL6rbiARLr27h7Kl55DuKLAc3ujIg9x3nvjPOlc6qEVMV2NpY4iJ6VYBl5Li/qvIAOJKy//if16S1QpybGkXT1A19Jr1k5oeC9AdOSfc9lh/fyU2V2zYrJm9bdfOiBRmw=,iv:9r7ujNb88/z+YAM0v1swNGM9Aulz09VxRMOx5p1xHC4=,tag:P4I3P9SPIfqYdhbQeVDP8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
