apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app guacamole
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - config-pvc.yaml
#configMapGenerator:
#  - name: usermapping-cm
#    files:
#      - user-mapping.xml
#  - name: guacprop-cm
#    files:
#      - guacamole.properties
#generatorOptions:
#  disableNameSuffixHash: true
#  annotations:
#    kustomize.toolkit.fluxcd.io/substitute: disabled
