apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
commonLabels:
  app.kubernetes.io/name: &app bazarr
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - config-pvc.yaml
  - poststart.yaml
    #configMapGenerator:
    #  - name: bazarr-config
    #    files:
    #      - config.ini
    #generatorOptions:
    #  disableNameSuffixHash: true
    #  annotations:
    #    kustomize.toolkit.fluxcd.io/substitute: disabled
