apiVersion: v1
kind: Secret
metadata:
    name: tautulli
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:BcYD31291oHecm00eUmZgQmDlYII5XZGjTfCMrUXgGay5yaRhfm9,iv:SC/GNo5kQoDn6eSCuIKvnvJmMY0PBLdm+VoMM2vG24U=,tag:kWW84ZV/pQOs6m0dzinstQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:NZZE2XapEkjRXNXeTU5xgtTOSpUMtsLwB3vxT0wvkjYdaYFt+IPyWrTtZBoKkAGRXS20QgjQ2mHDPFkvoFuPaQ==,iv:IpmvUQ+fYlW2sLMRw5f+c+xlFpfgzMys/mpTz0/FdoI=,tag:YBd3vrI43sIROdiNM1k0/A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aIVZhrGA,iv:11JQ4KemjymlON+igFZ3eC19xy4RgaIxoAF6qjsB6ZA=,tag:0jtK2gscC98ICOcvBqpxRw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:P+QGli9unyTNvj02Ho5n98hU5/0d,iv:MtMWka+zGcMu0cjlhO7WQBwgP+D9EeWBwu2JRKG6MMM=,tag:kkMwp3eQ+8AlqGjyArh0YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y0x2N2Q2bWgwUGRWelc4
            ZHpMcVNBTS9hNnE3YnlzcEVkZVJOMWE4SXdFCjNQcURsT1MxV3B0aWM2RHMyN2xu
            YmRIdUJ1clBXUzJxRUFOdG91SEY4azAKLS0tIFVEby9NMzlmR3dtajdvaW52SjBv
            b2s1MDBzRWFyTDBualVlaTFvZXFiUkEKCpqDr6Ej0/4ufo8ANxCG3oSvXbp5i4It
            00rjlj+O5DXkubLxpL34HaQsuKBfcypYkbLhFP8IcL2iXx8Mf8b+Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T11:36:35Z"
    mac: ENC[AES256_GCM,data:ruWdHkr1ouOotlajcO/I3BWEAWWwcfLrLOkZwM7Sf83gof7IiNp/6FruwOdk7WpJwWh7LYn0d1yVfqzxpEd3g8PoC7fMP4vl36xkeULQ9MJkgLs4C2I9Cw0wjudajMuEnbaGjT3oAlieKsGMyDY75xTLSONjokd0LJNSb6kTPMc=,iv:GOMtHWmHNWYNd0Xmp7ftrGgiShjDKRuM/g70DjpDpTc=,tag:hpfSnSqGAmJ3rp91bnWmNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
