apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: babybuddy2-volume
    labels:
      app: babybuddy2
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 256Mi

