---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_PROD_DOMAIN_MGO}
            - ${SECRET_PROD_DOMAIN_KAOFAMILY}
            - ${SECRET_PROD_DOMAIN_KAOFOUNDATION}
            - ${SECRET_DEV_DOMAIN}
