apiVersion: v1
kind: Secret
metadata:
    name: hercules-renewal
    namespace: home
stringData:
    #ENC[AES256_GCM,data:CPwWTeMPsD2OCdSE6+EkXsW4TXEL3FKHKTIAsV6AzGtGCfib3mLpJ8zrRfnB6+InIwCvGZwZgISOLpAuQWE=,iv:OILEdnPRAAZHfmILAfqdaRhsnBPHMO9FfC9eyDKcWKs=,tag:nMjDA4Ty7ICRCCWoljK17Q==,type:comment]
    MYSQL_USERNAME: ENC[AES256_GCM,data:l6SACUfVyFw=,iv:clMDFBpWkq7/rRUP+sxwoLDIF1yDUKuIWnsfkWkvKt0=,tag:MBxbBwQbFi5+bdFwra8ShQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:GaEVhy83aKc=,iv:BNJFeZDweRgwYiT8bCbF5wRIW+gv0H29oYQouCRvCrs=,tag:H/ueu5ePl7akZKzhjOzvWQ==,type:str]
    #ENC[AES256_GCM,data:o0PrpoP1F74mk/Nf/0kj9czPZMsJlkezrcKJ+GiXL0lbZoAhLFuWeoEeiskdnnAm5ETpn20CNuT37XVC8JA=,iv:+sL7Pfyj1nqZ0i8FM1LHkOyqjxJ0etDjA7phNKsgkxc=,tag:BdzBWobgPQtB/AL2D36JHg==,type:comment]
    #ENC[AES256_GCM,data:V8+2VI0wTAZd,iv:qHPhHP90+74ZWqqnauRXRhMV4d4zSE6XdlFcg24GN3c=,tag:TLR/BvIfDHsd5bHBK+xmgQ==,type:comment]
    INTERSERVER_USER: ENC[AES256_GCM,data:4moIAwN+,iv:72wlSVfk23Csjqqyv08kTSoFeXV4X2JNLCxbJDi+ASY=,tag:MfZu1TaDJWP4ajFyejQ/UA==,type:str]
    INTERSERVER_PASSWORD: ENC[AES256_GCM,data:zr4hBzHB,iv:AWN5uJ7qdpDcAwwmfQT5U5ylJDeEaxL+dApzvOXEfGE=,tag:7guEdUG0sgfcL9Gs8qkpJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaGdNVjg5SEJ6bUhJMHdX
            QllrKzBrNk4xNzl6MGhnY0JvYlZteHJBUWpvCmMvRzRGdGxyU1poTFpybnRrNEMr
            bW8zMWdlTmdrYThLNXlwY2U4UzBPMVEKLS0tIEpOdERQaXRiL1NRTWc2SW50V1hB
            U1NPM2pPZDBsaHRtQ05ZNEZvdE1adFkK861J1lzlFc01kVrTlyu9mXu5xSpCcWYu
            yAwtyX+qzvGtcVUbgUQhHqUFiUZdvXfyYY4jPcndEggK3ZQIqzikmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-15T23:16:41Z"
    mac: ENC[AES256_GCM,data:Ve3vC2INhAlSeMnxBXa2Ild2N4VdnPoI+Oa5J1gODozveYPLM2IrIfDTrKW1AhPv52wBvK8fdTx1gwilyhgRttnEZECMsRR8PQxg96+QURSpJ578GRfW7minZ+qjXGGDFG92baJPV/ujzU3tqi+Xm7ftBCncMj/yQ12NXQc3QXg=,iv:Z2IDxXy6QCUzWnBsT2PayThOE1UkA23OMVNa+ut89+I=,tag:yNpglybfjcv8WRMB5zeorA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
