# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
stringData:
    tunnel.json: ENC[AES256_GCM,data:jUgB9iZX9SDxrA==,iv:1U8O3SALrjilR+N471d9P63vZsy/E79Z9zA48q68Kfk=,tag:V5qqXl14zpklVg5LdOoBMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV1Y3a2ROTExiaVV6c2o1
            ZVV5Y2xVQUJFUW5VNlA3c2wvb3lxaElsckRJCjBnajZ3UGFXWkxoNmNvcnJXdzdV
            OUFCTG1IYXBsTS9GQzBZVTBveE1DTDQKLS0tIGZrdzhXSHpieVI5V3lrSm95WFhz
            Qm1GZENURVVYMkR5MjFOSjBGNUQrZjAKxCvbN7RiYT+kK8+aa2BuD8q2F+h49eJG
            FM/6h0HhDsRZmU3pBaAF2GqBk8OxbjDhn1xvszRT57pc3FvO3P+JPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-28T08:32:28Z"
    mac: ENC[AES256_GCM,data:A217imxcmGsHovkXpZ6RZ/4hLwZqnfCwlLVVZWhUgikI+9f9fSaoFs772aMX5QG1/jmtu+OCnGkKuO1rnsggYGvs0NBIWxyQ+RJF6YRDS5wwrlyTC4oxRdBQL9qNXhHvhaBh+ch/B77uVGdEELo8kQIlibe6O5OfuWoiTuXjFBo=,iv:w5gZhuW32vKySqToRisb0ki4COJetiYUMZc0MDIZ+ps=,tag:nbW/a1HeR7Y4ZAY6R3Drbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
