apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: databases
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:qMOtMYK84eEfVw==,iv:PktdV6cPbEopsmCBWAdUHrgC/TFcb9jly1aoOImoqzc=,tag:zFX/J/261w5KGnZQGCKbDQ==,type:str]
    admin-token: ENC[AES256_GCM,data:fnJuvM+hoKCHxOLRwxZfbbTPtmIucYqiGfjlZiyWBr/ClEW73HICUVSCUe0=,iv:ZXeIgYuza1Fmj9E61Yt9Y5Lu04VpCVmQpCbCLGPx2KI=,tag:RVZFljrxOSE20+HvqGK1Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZVpIWFRuMmh1b2M5N05G
            Vjh1dFlPbkcraFVrdnFJNjFjYzlBajdEeW1BCnp6cVhiRkZrV0RSTTlUZlowbFg5
            WWpBK0hZMFQrWGNuekhVanRJTnFvS2MKLS0tIEZDdkhzODlhOXpwSWJiY3c3d0dy
            SG8rK01vaVkzZkdQdXN0UVlWc3loQU0KFCzwopU5Ja7ejm4W1ruy3SOSGjrCYl5R
            GtJ5b9ypiZ++PX+P28Injv8ppnHwD8srNZ0B3CHaI53VFgEbVYzSFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T07:35:45Z"
    mac: ENC[AES256_GCM,data:pQ6zpIknFuqN9xyhvhykGDXQ/CV5LVVvVAioL5M//eSae/Airaf+QiFWwwpbY36PROezg54bF12i8TTRUViQbwesxZL8TnY5m5s1CbQ72wVyR89I5uK7BfXlEsLCZR0OlFpluYrKakxoWu//8wzvr/kuoXgABb6fznOpiccAMiQ=,iv:T3UXknx9yJAiNAyJY/pkv+M0TN0E21m+2Isyif0IeaM=,tag:OaUP5Nlv405xc6f7GJ8jSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
