---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apiextensions.k8s.io
              version: v1
              kind: CustomResourceDefinition
            patch: |-
              $patch: delete
              apiVersion: apiextensions.k8s.io/v1
              kind: CustomResourceDefinition
              metadata:
                name: not-used
