apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:nQOsrX7xyBc=,iv:0qRANv1zgh1jKL8BBcGHEMko39cGGfTLdRezWEeitXI=,tag:ArIApVYpq+YOet2pRhU4bQ==,type:str]
    password: ENC[AES256_GCM,data:27peqMwEE5vDdIBMoB7f,iv:GtnpL3acVuvd0cD4Qak8UCPTB8lvpdsQtqwxzmFvYhc=,tag:VHG500RS9+qrnmtSKQAGRQ==,type:str]
    host: ENC[AES256_GCM,data:Z7CyiCgxABowcrqdFgrM2uMXU7ZCtlppXYu4nQVkDL5nXdiRzZgggA==,iv:4mKGkNRFkOmkQPKnoawATtE3HChLCWEgeg6SCXfiv8g=,tag:lZGpA4aMK7Kw111aRL2HkA==,type:str]
    port: ENC[AES256_GCM,data:EwGElg==,iv:ugfbkXi96+GDhQbe//pYsjunga9VnM305+tcSXk2xQI=,tag:j9RdyO0smb9KZKuOD3enBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZUhCYkx3WVkxU25qNGdv
            NENtSGFRcHdxZFlpVHZIZ2hzM0FRalBldWlNCnVNL1BTd1hYNWlPS21hOGYrWnFp
            K2hEZHBCajJERExvczByYmVkRU41K0kKLS0tIEY4akhjaHVXS1plTmx2dWQxL2c5
            Ymk3SVJXSmtRblRxN3B2MVJmb3h0Z0UKlLh7g13DNnY0+OnCIWes56EvN0Men1Yr
            bHz+1qJHZYFFhB69r7xtt+x2Y9DvR9rXStY9QxuZHpxBhfU0LQwaLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T16:53:23Z"
    mac: ENC[AES256_GCM,data:guRLnoHfmWNikmxPZNBLmWPCsyPJCc85jsJKxJI50qWeP5BzZ9GRqqD3AK9SYQG3rqllUfZwGc4UOS7iKcKz5o2ESEFOa0ph90PpheFNiL8p/XWONoibgnfszyEDzk0YFc3Djc/EQN9bW+Z/NhBWR6/uq4eiPdhMTLCPo19CT2E=,iv:oufLosmjnS89XC3RAzeFkuxAioV6zskE/Z4kpUVTG0s=,tag:VxijW8YmEUduFu1niyrV1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:XaohIZpixLabJRcGAg==,iv:vtOUIsjELF1TLWc+TLjEj7TI0B/tO2QA+gg2koNY6SI=,tag:MeBCXsmcZYQ63bdqR/O4jA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:LaPMKzsGm5odI1mDco486Y3bv84=,iv:haym6Df7418AIoX/EWz7K/HBfa4aKBoZDkX70xCSIt0=,tag:VbIjuBMGSdxOYfbgYqx9gQ==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:+79t6Ls=,iv:YbsZCSZB3llOAh946TQv4DCZZIWzufHjZ7x3xF77+Eo=,tag:WSNGnG5nPv6cz8jf9h8opw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZUhCYkx3WVkxU25qNGdv
            NENtSGFRcHdxZFlpVHZIZ2hzM0FRalBldWlNCnVNL1BTd1hYNWlPS21hOGYrWnFp
            K2hEZHBCajJERExvczByYmVkRU41K0kKLS0tIEY4akhjaHVXS1plTmx2dWQxL2c5
            Ymk3SVJXSmtRblRxN3B2MVJmb3h0Z0UKlLh7g13DNnY0+OnCIWes56EvN0Men1Yr
            bHz+1qJHZYFFhB69r7xtt+x2Y9DvR9rXStY9QxuZHpxBhfU0LQwaLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T16:53:23Z"
    mac: ENC[AES256_GCM,data:guRLnoHfmWNikmxPZNBLmWPCsyPJCc85jsJKxJI50qWeP5BzZ9GRqqD3AK9SYQG3rqllUfZwGc4UOS7iKcKz5o2ESEFOa0ph90PpheFNiL8p/XWONoibgnfszyEDzk0YFc3Djc/EQN9bW+Z/NhBWR6/uq4eiPdhMTLCPo19CT2E=,iv:oufLosmjnS89XC3RAzeFkuxAioV6zskE/Z4kpUVTG0s=,tag:VxijW8YmEUduFu1niyrV1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
