apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: defualt 
spec:
  isCA: true
  commonName: TheKaoCloud SelfSigned CA
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: ca-issuer
#spec:
#  ca:
#    secretName: root-ca-secret
#
