---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname influxdb
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    podLabels:
      app: influxdb

    adminUser:
      organization: "kaocloud"
      bucket: "default"
      user: "admin"
      retention_policy: "1w"
      existingSecret: influxdb-auth

    persistence:
      enabled: true
      useExisting: true
      name: influxdb-data-volume

    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      annotations:
        metallb.universe.tf/address-pool: dev-infra
      labels:
        app: influxdb
      portName: http

    ingress:
      enabled: false
      ingressClassName: "traefik"
      annotations: 
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdiPlayNetwork"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hostname: &uri influxdb.${SECRET_DEV_DOMAIN}

      tls: true
      secretName: *uri
      path: /

