# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:NjLxoy+Ct7zWRvlzdQ57aJysyQ==,iv:WxBCFZuYhzhKySgnDOMJDWyZz+9bVK/w/1hh6AuuULw=,tag:tSbW8raBfHJh6PftfiSE9g==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:0zq1+/UykE8c3pPhPzdp0tBhPFdPe+h2xNQM6ac=,iv:8Yu3Mcu3dVfXaUt6NrVlRwYy5wMazxC1H3SAvuSx27s=,tag:ytKPhV3ksl7KDpX/NCemGA==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:+BrCMN8HJciL6KZB1rmlFbEFe3uGYTEZMUaR0Q==,iv:Zh9bqsI4Mf5HTtqEl0Z/1Lpe88TpRurFNEjBZa86SKs=,tag:Rh9+HwMAruurLlVEDgTAmA==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ks6X5yTK0U0qBuGIYYLLoBLnMtTIXSbnLYYbi3whFBcsgGRokg==,iv:W58l+NRe3UCl1iUY2QRq8I2X4D3yedwwybawZQkI1RA=,tag:pQVZg8vwe9xL2rNTsCQuzw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vIQCVPUmgiaSyBK1QSUxzJgE1+E6btg=,iv:FJJBz0lkrnyGruO83eshknIcqXJvE4jzW/NNrssn41M=,tag:lNlgF9NQqrB77GJsvaX1qA==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:nIzJauD1JqIDyW/4ehW0,iv:J4zfBS2PMgzV8EgLO5n4Pp+LjdTt0Fmr745LhtwRrbo=,tag:wfgSNjfEvLU/Y0NxFqlLmA==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:8tDX4GPZOQwn5g==,iv:sNtlVYl7Bo4QPf+8Hv1w4K/J+MwPVn8WWrTacBDi1OM=,tag:AqdJQNq3SUvlBLRK0fNOoQ==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:d/gkKwaUaHpg9sDPHi4=,iv:OXmxWU81LUMyuqaAL/xDuSxZAva59lP5oof8CPFM+xw=,tag:EcXX6Pbs5Eg/KQ3FqzlRCg==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:CTZsKBNTgJA=,iv:bAYsMInwP9RXd/A2+caK+/UUBi0SSSaUJmfaPB+G3bM=,tag:2sO10YfEhTQcYsdkHJBG1A==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:Drsru61kqJaMMMI=,iv:FoVZqm764qP7E9y43cHolQ63aPPCw8uF72R2wZqRmz0=,tag:BK08WrBwedcrIoUpuVOEYQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:2IpPJYsUVT1+Ebg=,iv:oKgoZTcABZzzquIS3EMqcjiCvKvEY63c99vptlRSq7U=,tag:sfgt+yHtXUZfpkbJ2xR96A==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:ZF+IyTzFsNCA6ozMJio=,iv:GrtmBksrv+MsRBdPkejnccDcZXgOR4Prz59RfabdCRo=,tag:ydaGkmxTvtb1Rlb0yT1xDQ==,type:str]
    #ENC[AES256_GCM,data:LUc1rJ4p5cxDktz/F+/0g5ll45kx5RRploey3X+OSw9K5wCF+B2/gh146+pRFRAOwdCWNLlinoZuXpBtpA==,iv:NXKndKNmfwEYobKDwJQhTMJFYjtRYXf2O4oi7OlVuts=,tag:WobZpWt+TvelHawONYyC7g==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qcVBAGGyr6+aZOHToZGaPqhWcIpQkKRsE66JhcsxGlsyDLS+uEVALwVJcLODNJNtKpmcZD8V3iRC8Gg/GJqAEw==,iv:VXrCWzw4peR6OrrYUHXV0NNeemaYQK3AcuhevZNKj3Y=,tag:cnqOIuZVYJjphYbqzPCpNQ==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fFf8VY36ha9ATh+Cr+Hi0cJwp9IcfHPUOiTBHQEszyJqPZ7+3ZuV68MVwfSEJhNONTOrJTQYIPANkRbGcQAIbQ==,iv:r1KU/VeQBgX5r0ZfLJvADYxRQFJkgu1I3du/2cs+gks=,tag:63k1nXazsKhtvi6A/bXqug==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PNznVFejGuLR4kUP3lIlIwvLnDmHwg8EnPYJji/jhxKXlHser4ZsBm/+FCd0VyNqG4MPIRG9FRcBaWi+Z/5vfA==,iv:AdrDYu+hBI4iyUXl/owFGNYndhK1i+VwhXEsdZWOm88=,tag:Gi9b6jDgKQTxR1CHQ+NvwA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1fE/evoZ/M4PLQTwV8qVHnDFSED4khGIWhNpgyzOS3lyYCzbcB9NsBFQPKKQztcON0jQtnktuMCLK74XEpTe/Q==,iv:0ErLkxYpCjCJbqftGhlfYBC129vAdVnGPDpdB/D6ECo=,tag:kRJ55MBc8MoUSY9r2w1CBA==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:mCB6dNRS+E96w9Goqex8bIEAcBGaR2qA7fYaycd+GZOX5zATlD8VTf1oYX+7zyRBZSQycjEU+Ih+FYrCbEEKUw==,iv:d6IEgZ4cmxRuBPUfXbMPEkfNFeVwisUglFq7DwaZwbw=,tag:/NksB6U01pY3+11LDSuHhg==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:siSjDzFKKWPkfz5dZXqutpdUYECGzESXTRs8J4F1g5czF2ziOVYEBFUaRZ/3owiUoguA8/SNxp5QaogT/Jjbfg==,iv:Vt8CbHAG0mh73+e8FgYu5m6XXJ7G44J9tliWJeqDslI=,tag:MXe+C07+xgbHIKocJOV5OA==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:W397Cp+NwvsQ,iv:XN/tUtg54jqYDTrgNfdAaUcBqAVNGPrYPft8DAIbfQ4=,tag:/bs2494yLYFrucnsFvoMEA==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:HV+6GRCYNBTOknHs5/g=,iv:Z0CPb75bc2KXSKVCbownw3YwfSKJXVOzSYBsuACcbvs=,tag:/aydK+ZX+NybKko81p/xFA==,type:str]
    SECRET_SMTP_FROM_NAME: ENC[AES256_GCM,data:MC+f/YEihNVh3Y84ug==,iv:HT2UWdZntOxtH0Qsm0gk8JsIKjltv0kSJApWVmzTcLQ=,tag:Aru4cvQEh7IOEHuM+cFl8g==,type:str]
    SECRET_SMTP_FROM_ADDR: ENC[AES256_GCM,data:9QbofEnxDcOXGhfdFjGlekx6eu27,iv:9NeffPrqh/mvjnuCT+N706pv7lfH2Yv6nkOQr/xfA1M=,tag:UYb6hEPy3p8FHY0+SoJlsw==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:YigvNoKaw6sPaRuXjVBft+PMGYDL,iv:5h+dspdyF5NNx6E4VScYXVPhDgeJ1d/r8eVeCXo7maA=,tag:gpTVwnwZU4NqxByVz7957g==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:mCWZrawF3ZbII5RjxGID7w==,iv:QoSEo9GDiIz44eZMdJ+eAPK/ZJvQEGRp2O7E/s/73DE=,tag:n9Idde48nKLywPzHzezUqA==,type:str]
    SECRET_SMTP_SECURITY: ENC[AES256_GCM,data:jMh+eEBQrx4=,iv:LUzMFHkaeE2JQPTBY008H9dXD6ZADAkzNCe5jYGI6t8=,tag:FrwSjl4ACet1ncb3kK/Lgw==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:9jvW,iv:OEw4SlmNnuOJKcCyQ4odKr3CsTTFfoW/6Ct9sRI01m4=,tag:sPKz/dkhqj5zbiBINDMn2Q==,type:str]
    SECRET_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:/3AUFF0=,iv:dPlTkHIfMNXhY22mzLaDSp6XOt60t4qUPKMQ0VQwQ0U=,tag:tHLeRtOvyv5DdX1azi4aWg==,type:str]
    SECRET_YUBICO_KEY: ENC[AES256_GCM,data:Hu7KBWw4ypuqGbJHu0tkuc3wLfzZeVFMZuKS/Q==,iv:QbXSlPOUjCBxfHJnbkQGAyPagHu9+z+oja3BFMoOOdE=,tag:AFntV6WlENCVryKzRp7iwg==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:TElmUhnCucfJXErIzxckrqpf+1kpIysXCcVqB1YE,iv:do/Bjg8W10s5MBLTTe9MIPXP4wf6EtS0riW8NaYiZJQ=,tag:Voj5NrZflD9DX2Ieimay7A==,type:str]
    SECRET_PUSHOVER_EMAIL: ENC[AES256_GCM,data:9lIoVX5MMu6vHAul6fQzck7OH94m,iv:MWtYVQcj1XVPJtqB15l5SUanmO+vHpVUjbKeumn/QcE=,tag:jUThUSP89UTNAB2wvD5/xQ==,type:str]
    SECRET_PUSHOVER_DEV_TOKEN: ENC[AES256_GCM,data:yDzkpR47XD7CA3lWl2rN3mq0njBKC2J3biueHVxH,iv:7jTrQ/jONwGurEr3v2JJCcaPmfVYDm2z6FoD7164UN8=,tag:3GZXamjhwVavEK42Cku0Lg==,type:str]
    SECRET_PUSHOVER_PROD_TOKEN: ENC[AES256_GCM,data:lD0tcUYl8LJBdnvNKy9Ba2Jso5STIwkoHT7b4o6a,iv:up0teTvPmV0H6QwRvAlWFQVcO5InQR0T6GKHfQgNFM4=,tag:ZooPIm9WQDRZynHAGXagzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZTRpMEZPdkMwYlBzZU42
            enBjc0kzMldEc2I0V0prOHF4ak9UblV0Q0dRCk1WY0NOeWlvbTNLRE1xdUNNb0Jl
            aFNrZ21DTm5TelFsVU9idWdteHFQSlUKLS0tIG9IY1IzNjJBMFVNQXpnak1FOXVO
            dGV0SWFkTWczOG1ZZEZrWDZVWVU4U28KGPE/2v/fzd6LZcuX9bbbPRHK2FJmFCwf
            pUyP6UkIKqogZmY5v9emBuiKXKlD84hKeuAVnKzxx4PM87+1cYXXOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T07:28:09Z"
    mac: ENC[AES256_GCM,data:zQWSGPh8lFOstJABCXY9Xx4YcPgxayt/T8fIi2+IkernzQYHoFuBagDCWYrmV8Et+obthOU5sklybUM2jMmBxngTtlFWQJRuGY/5dUliKxfllAwTaZ+DSxl1HvsQvXqILdTUws72KYUpds76JLI7zdH1thEZvevKCgb88aE6ugk=,iv:LezwWosl7zheZNekH8nlKxcRUTtTJgQz3WtGo8qiZMc=,tag:I/8s3j6WAQcd3tXk/xDybQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
