apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mariadb-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:DL2MGjgWfRAagMH2dlcWp1qEoRUSPEY60vpiW7ZhXkgTvBAiOio=,iv:Ci5VX+iXau0z3Dc3Q460Q+W1BbKV7+jfEpEFw7S6Lpk=,tag:93c/UmLrxdjD8GcHX7i46g==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:bXHo0NtPizfURsp0NcYDCfBRbhBBgYApQ2Oq,iv:KSuW9KFHO+TjuqMp7sSPEoTvNc9IhFNHwuDsfYD32Lw=,tag:FshrJMusdb0dxB0XfnpVWA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:Qel7xv7pkHY8yJdlsQc2KOiAnrzY+g==,iv:6u6zS25OD+XtlL+vU3rWoz7DF5MgGRpxe3NPUQZjX0Y=,tag:ulOXyXhERectuwYGgEFS6g==,type:str]
    mariadb-password: ENC[AES256_GCM,data:AzMx2Gjq4c4wqIHZmgdAQ0/slVx81pFQQXJmzM0=,iv:ctQVQHQgcybZb3RFfeelVjtyu8OQItcEuCMxnTfSXhY=,tag:TTVgC9CgGg+uYFWgLUMo6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYWtvTHJWcWNINndSYlRm
            WUJiak9iR2IyekpEOVlhMlFrTDI3eW92ZmdBCks2dERwNFhVV2lZRzgvb1NKK21I
            TU9qVW9rOFdWWFJMN1FIc3JqZ2hmNncKLS0tIGZ6NVc3RXRBc2dZTjJESUNRdVNp
            TTljN0NXRUF4cEUyOW1aS3NUQ0RRRkUKxDeCp4Le5MCQL24V823B+l8Ir4Ug5ICZ
            1MiGCw4xi7CfQB43DxtO5ffvO+btm6EwiKqJ0RLjFaiM+4vElNE9xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-13T23:06:48Z"
    mac: ENC[AES256_GCM,data:hl12OnGJz6WwmyiJaPQygvzgsVpHEB73aoNWZLEWzhcMs25ktyiMqjQbj/Ik7ilo5CNjC63sUxn9InkhdPWhKSW4qaf+8XpAKYutGYJqYYf0S8LUtSQYN2Ti6am93RtVzlj1fi7xPHaypZ859zCIPkZd1M/GRXvXEy4PvQ/C5RQ=,iv:A7BUauVyDj3j+5yYooDANUDm1lu0mkO/MiuGlgkw+6o=,tag:SlHU+CSCTXHYo24W0XaKhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
