apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app home-assistant
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - secret.sops.yaml
    #  - networkattachmentdefinition.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
