apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home
stringData:
    #ENC[AES256_GCM,data:FryIMeUxPn4g/gha4fzve1ayiOKB3ML92jnglBZphiTXU95He4o6RxRSYw2xpY/6Fn2fng0Azw==,iv:ekFYL8KHQGZLw67zJ0mXDqH2EWUvUGnfRTIXIqmfgbY=,tag:Tzns06fgC9GJHt0jOrtsMA==,type:comment]
    #ENC[AES256_GCM,data:1z5Nj8e9RPiCLNSsepuKen91EBUHI6vIghr/hiDgSW/H+zLgTvSyGuhMpcCetmVRyHhR1iI=,iv:z0i6kNsgk9ZnlBks6sTfWlxsM5h5NiRXCLWFp6dIdUs=,tag:nuWUxezJIACxLzCgOPeOog==,type:comment]
    #ENC[AES256_GCM,data:Iy4kEaPWejl0ax5YLKJ307LiByR/pjWEm/io2A8Q5CU=,iv:qaMWo9UGH55keAC9RyvKu7C8pd5dskXI/QtwritSXlo=,tag:oyo1e0sot6W/oRjCe5XrKw==,type:comment]
    #ENC[AES256_GCM,data:C9ZmdUqiow4ngASWK5UjbytCxCgnmk150FX+MxiQ3UFfqdga2+duXpj3EPtxt/FkE94x1aG0UbKeMno=,iv:VwIpdGxHcz41Lr82eGw/0qoTLV/vcb0b0D3y2azKdTs=,tag:PF0KS86Tia29VWKCsoJFYg==,type:comment]
    #ENC[AES256_GCM,data:Z5ANaQMDNax/L7OtmfLdiZl88x8D4JldXkX6mYHpfq3v6WVcMsqkH0ZzWVHID/wglYbFd11CUrziawu64u0QIuEAEPXmeO3omvTK,iv:Nn58uw6SNra1CySkSTJyVop9U0wLwtd7McFeXCYVDP8=,tag:7LIEKn92y9CBuzSzxug+jw==,type:comment]
    #ENC[AES256_GCM,data:0ts7ulBa1xVjf55Wmt9RCY6WafP1dD3vGRA=,iv:rbxHRCdht5s0dD7pgQke/rDxNiktvhSby6aK+IDvwhA=,tag:ce0bCfYu9RWYJsbtZyShbA==,type:comment]
    #ENC[AES256_GCM,data:rHmP0wYmREg+Fp3WVHQeQ8YJmASRpvdhgcThxg==,iv:nkCKtqVDrcoBjba9KH25EWlKTxZ7J7pHfBQht5ydGig=,tag:eI16A+SHoN+CP2qZlCHM9w==,type:comment]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:fmzuQ5qpwTr49dprtCMqOoWwxpSrYub0OcBxK9x4yjBDHkkrG8yTW9AibWt0IeospPpPwwKXwNahUbtv5AEmOU1oj/uvIQWRmxi3c+uFkHEhS7udbdERWLwIZJQN,iv:T27eWzDgNNtljvSNet63t+2Tqyyhu+I2c5RgbDJmrZQ=,tag:5dHtXy5QaXY9lBEyaQeXjg==,type:str]
    #ENC[AES256_GCM,data:31xBxx4W4iB4CYOIBYs=,iv:qCvYmxuF6m1DMDYAU9fhxV7lps/5EGwiAhj2wnAA5jY=,tag:2rdajDSA5F8rkflDxvKcCg==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:UHtXv9QY55ReE8Krb4E=,iv:chNFEE74bvG+CtQnftnNX5Xcs0yRPxee2lhWmNbi+Lo=,tag:3NkbkMkG+Sl2CquWYI/LFw==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:PjjR1KwrjOgNwnb6DiwV,iv:qfIGsvq6s9+dma4qDNtbJ6NX6bB84SzkKy69YMXdxN8=,tag:88xQaPUFM31F6FOhr3dgUQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:DkuHNg==,iv:eQaF27rxBI2m0y4D6R4TywQX+ehfc3DGYI1UZI7Lkus=,tag:npT6j4ZLgChNd8Hd9FpnsA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:50BPhBPbGbHhv84dJVxOBee9XQ==,iv:NeyCAC6vAn8CnagQbcK5iOfAUDAI7bZngAtrJTvHga0=,tag:g0e37+mx4qDXF7MUvuVrRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVjNJK21RS1Z4YVRkMDVa
            RmRTMW9VTDZzNFk2bmFRY0xqeWJjbHk3blc0CmoxQkwzcGNTRTZxb216ZDRiZlpR
            ZGV2NkNiM1BTRFZob2pjY2prTUc4R1kKLS0tIGw5R1hxNmhRMUUrMnVHZjk0cmNX
            OXB3bVhHTm1ESytrR0ZDZ2dvRzl1ODQK1UMMZLhUg8W+371zIcJ39fcwE1G1WXmt
            l+uBwdXMmYq+u8YIbnMWxF1XB9gH4rDpiIRbd7vL7HWv9jrrVVSQHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-09T06:52:22Z"
    mac: ENC[AES256_GCM,data:wlpmNi1CoY37JSV5gomJ8HbmQBOcCq2qtWp7wOBmWvGbZXzScsjsmSHAiPkykxQD+Ix0OCdkwdH5n9SXfY3XNQlp/2q4yNwDPjtOXqaYXMzV9AjSdlDIyscs4rNy/i5r2OAEM0C39Bd1krQy9Op0vwoZjIHaRKSLsBE90Kl2OuM=,iv:xvMu+GadhenZI7R/aWY3QA7YKwcdjxNoG7rUmCZQWPg=,tag:0TJWuxITkQbzPBtw0dQhTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
