---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden-ldap
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/vividboarder/vaultwarden_ldap
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      CONFIG_PATH: "/config.toml"
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    service:
      main:
        enabled: false

    persistence:
      config-toml:
        enabled: true
        type: configMap
        name: *app
        subPath: config.toml
        mountPath: /config.toml
          
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 128Mi

    nodeSelector:
      node-role.kubernetes.io/worker: "true"
