---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-redis-secrets
  namespace: kyverno
  annotations:
    policies.kyverno.io/title: Sync Redis Secrets
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy will copy a secret called `redis-secret` which
      exists in the `database` namespace to new namespaces when they are
      created. It will also push updates to the copied Secrets should the
      source secret be changed.
spec:
  mutateExistingOnPolicyUpdate: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: sync-redis-secrets
      match:
        resources:
          kinds: ["Namespace"]
      exclude:
        resources:
          namespaces: ["databases"]
      generate:
        apiVersion: v1
        kind: Secret
        name: redis-secret
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        clone:
          namespace: databases
          name: redis-secret
