apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fasten-volume
    labels:
      app: fasten
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 5Gi

