apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: babybuddy-ava-volume
    labels:
      app: babybuddy-ava
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 256Mi

