apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname babybuddy-ava
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 16m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    image:
      repository: lscr.io/linuxserver/babybuddy
      tag: 1.16.0

    podAnnotations:
      secret.reloader.stakater.com/reload: *appname

    env:
      TZ: ${TIMEZONE}
      PGID: 1000
      PUID: 1000
      NAP_START_MAX: 23:00
      NAP_START_MIN: 08:00
      CSRF_TRUSTED_ORIGINS: http://127.0.0.1:8000,https://babyava.${SECRET_DEV_DOMAIN}
      USE_24_HOUR_TIME_FORMAT: true
      ALLOWED_HOSTS: babyava.${SECRET_DEV_DOMAIN}
      REVERSE_PROXY_AUTH: true
        #PROXY_HEADER: Remote-User

      # -- Set the application database type
    envFrom:
      - secretRef:
          name: *appname 

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        existingClaim: babybuddy-ava-volume

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: baby-bottle-outline
          hajimari.io/info: "Baby Buddy Ava"
          hajimari.io/group: "Home"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
        - host: &uri babyava.${SECRET_DEV_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
            - *uri
          secretName: *uri
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
