apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app onlyoffice
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - middlewares.yaml
  - secret.sops.yaml
#  - config-pvc.yaml
#  - poststart.yaml
#patchesStrategicMerge:
#  - patches/patch-postgres.yaml
