apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 31s
  dependsOn:
    - name: infrastructure
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/core
  prune: true
  wait: true
  timeout: 2m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
