apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app localai
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
