apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname nzbget
  namespace: media
  labels:
    app: *appname
spec:
  releaseName: *appname
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 6m
  values:
    podLabels:
      app: *appname
    podSecurityContext:
      fsGroup: 568

    image:
      repository: lscr.io/linuxserver/nzbget
      tag: v21.1-ls136
      pullPolicy: Always
    
    env:
      TZ: "${TIMEZONE}"
    
    service:
      main:
        ports:
          http:
            port: 6789
        type: ClusterIP
    
    persistence:
      config:
        enabled: true
        existingClaim: "nzbget-config-volume"
      unfinished:
        enabled: true
        type: emptyDir
        medium: Memory
    
      omoikane:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/omoikane
        mountPath: /omoikane
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "download-box"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "nzbget.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *uri
            secretName: *uri
              #    nodeSelector:
              #      node-role.kubernetes.io/worker: "true"
