apiVersion: v1
kind: Secret
metadata:
    name: babybuddy-ava
    namespace: home
stringData:
    DB_ENGINE: ENC[AES256_GCM,data:LVn+UwlPB0V0JITWLvn/gLAZzOSS+NgQC9r7/14=,iv:Sb7LEb/98IKf1YkM6SQRqzcvlVce1nV2wgIo02Hp4hU=,tag:jQx8lexH06XgvPcxFyErwg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:lB9b2zWZIQUCanF2RQ==,iv:5P5fARgqb+bIsYtCiL9ECxOxm2nPtT/i7itQzlFEUhE=,tag:nmsLHwekPH6UTmojDyCA5g==,type:str]
    DB_USER: ENC[AES256_GCM,data:pj82SsuhxwAcDzvciQ==,iv:WJUV/WgIz48Q+XfqUsp5uh8hCTM+0eRODL9PGnoEbiY=,tag:qlK8tV8U7BhfgSbwj9GtQQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rKyjsRSHWCxHq2874rfP+T0Q1QAWZHwoxG/gtgfn7a157KkRjibnku+J5s1bFmEyaL7v3Im9FZ90QcrkxalCOA==,iv:Kd9cw+zmpUdI8v5qrqvYWB7kaG0++M/q/Dr8xQ8ffkc=,tag:D4aDCW73RG01jQrz4OoLvA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:EQIefbHc9plhE9unvRq7dEDwruqBo7y9QPr5qFyryQfzCWhxQ38LRQ==,iv:fzl1VULIVzA4u/LoUpPL5AU2mQkzd9xoWAPi0KvafM0=,tag:96ewmDMP+rQdLYNXo00MCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNFMvMW5jRUtURGxSeFN3
            ZEQ2R2N4Z0hSLzh3d2s1WW9scjNGRTNWbkE0Cm1GZ0Z4M0ozbm9xSnVrQ1BIbnk2
            UHRXZlk5SHpzRUVOZXNOemNXUDc0N0kKLS0tIHFnMmVPZ05RS1VrMERnVE94ZEFz
            Y2JKNXhXZHAvc0ZUOWc1eUpERU1UTzQKPNXRXs/TugCzPQtmI8MFRzU1QXIj8Fz6
            76VBcsZDxwfzrA0pPKRXDMRGpiZg9md1cS1RhpSqYlfkVgJzpqzrXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-19T09:05:41Z"
    mac: ENC[AES256_GCM,data:vJYQwIcKj10guv4UYIWiJ4eTOrF0t5KkH+lrcixl1fKRmuOk16SxjvL5bLkfUw8SBqtR1woq4PjemAhwb6O6RZN73ytrUPH0SI0srV7eqMaFXkqz8+ToduJ7WRyup6zWQqCGWjU5bCk3wihJGQKpfxNEYHEK3VnKWNKDftXuJJU=,iv:6MpYvsnkD5buxgiEdR+crHRz0fzM6AnCvGgNuZuDbJk=,tag:7ewAV32Ni7FO71L5DADiiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
