---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app guacamole
  namespace: default
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.5
        env:
          - name: POSTGRES_HOST
            value: postgres-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: &appname
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
                namespace: databases
        envFrom:
          - secretRef:
              name: *app
