apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nzbget-config-volume
    labels:
      app: nzbget
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 128Mi

