apiVersion: v1
kind: Secret
metadata:
    name: hercules-classic
    namespace: home
stringData:
    #ENC[AES256_GCM,data:omhisENVIXYvAqr2be1nSCFqVXkcBggc3ae/RkkLaI7JAzK9tQ9oQfe9qy+qW6Ljmz05AzWzuizExtMLos0=,iv:aP+DoiuEhPD5L1irM+F3fi4d8x4FYvKkZYL3xoCYTVA=,tag:sC8gE36oM39lH/oWZAUYFA==,type:comment]
    MYSQL_USERNAME: ENC[AES256_GCM,data:rfCybcpi/+o=,iv:yG2juB7AS48ieOOjiTj5/VSWeoCqhTxwrvfPKgHP85c=,tag:SQu5PK8Ns67vY5M6dtMnSA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:69pOhrlmDe4=,iv:US1NuoX5cGTn6wRRPILF0yoy0FOqiKazPkwAk/Fkfn0=,tag:NSABuLKRKdiq2WsC/4+iHw==,type:str]
    #ENC[AES256_GCM,data:U85I+u8BetZHmQPn7tfkDfD3ofp4bzZ/CYYbpfyJqr+JLzAZ2yN6pahuD9xkHbyEPSv/IAb9twRLBXMDHEM=,iv:CEhQxHRPO4FPHqKqnP+eZyvKHw0b/2wQvId5ZYYG670=,tag:1ncDHzMg+TNvJjHd8X/5Zw==,type:comment]
    #ENC[AES256_GCM,data:GsDDWoWqfSap,iv:zqOsHF8zFdGuL5yumYmbAwTZ/NDURl800HKkW0OO85U=,tag:2mYPNYHj51PivASgB/w9gw==,type:comment]
    INTERSERVER_USER: ENC[AES256_GCM,data:BXlHBtXP,iv:zcp+h+EYgP2aV3jo0WK69d4cgMrXMnvPdALY2YEmQFA=,tag:DRQCFtug+nnmsP4giIMG0g==,type:str]
    INTERSERVER_PASSWORD: ENC[AES256_GCM,data:IqPW56zN,iv:2Tbmdz2CdM+fArnyG2vJURMHCdgLQf2+d5Ho6MlTGUg=,tag:7XORml98jTPspxsa+kVHpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic0ltWVVhL1JDY3puVjd5
            bzFNR056cXFyYXZnR3NoRHlqOUxoUUk4dldNCjJ5S3hZTWR3cUJxOHZySXVhclg3
            L2dBOHhMK1hrZXppVldkL0UzUWYrUTgKLS0tIFdOc2RmYStYOWM3OER1U093SkE1
            bG15R25iOWc2TlNEZVdZaXlESm5yQU0K0NxCMKAnFtSOR3ncZIB18O+txGjbWKBe
            Upnc9E7ar3BhGgHAPWpjPSjA+7JmGUpnQZDD4bWtGn+WoFSmUpwGvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-15T04:20:51Z"
    mac: ENC[AES256_GCM,data:DnD84xt4hnUEMY8XICsBUY5q3OK6vJjdvDqq/FFtZ0lhzXJa3XFAIRIcq6jkz+ukxyDTzSHhVjPx2pX3IH1j/R3F9sttb7x+nK4we/EAX5CNfUahIqKL57E9QYGFh0yf7/5gk9yplWhUweaAhztkH624cGRgmrA0hnjolyOGzSE=,iv:eF3VPQl0VLq/iQKrGY9bASQrPgqJZ+zfs7PeLBGE8Rw=,tag:z3mWX3Roy6pqgtih+zkvYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
