apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
commonLabels:
  app.kubernetes.io/name: &app plexmetamanager
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - config-pvc.yaml
  - secret.sops.yaml
