apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
resources:
  - helm-release.yaml
    #- patch-local-path.yaml
    #- backup-secret.sops.yaml
    #- recurring-jobs.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - prometheusrules.yaml
