apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: hercules-renewal-volume
    labels:
      app: hercules-renewal
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 3Gi

