apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app authelia
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - ingress.yaml
  - secret.sops.yaml
    #  - service.yaml
patches:
  - path: config/patch-deployment.yaml
    target:
      kind: Deployment
      name: ".*"
