apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: networking
  annotations:
    metallb.universe.tf/address-pool: dev-infra
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: "${SVC_AUTHELIA_ADDR}"
