apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media 
commonLabels:
  app.kubernetes.io/name: &app sonarr
  app.kubernetes.io/instance: *app
resources:
  - config-pvc.yaml
  - helm-release.yaml
