---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chronograf-data-volume
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
