---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname chronograf
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: chronograf
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    podLabels:
      app: chronograf 

#    adminUser:
#      organization: "kaocloud"
#      bucket: "default"
#      user: "admin"
#      retention_policy: "30d"
#      existingSecret: influxdb-auth

    influxdb:
      existingSecret: chronograf-auth

    persistence:
      enabled: true
      useExisting: true
      name: chronograf-data-volume

    oauth:
      enabled: false
      generic:
        enabled: false
        # client_id: CHANGE_ME
        # client_secret: CHANGE_ME
        api_key: ""
        scopes: ""
        # eg. http://chronograf.foobar.com
        public_url: ""
        auth_url: ""
        token_url: ""
        api_url: ""
        # optional
        # name: "generic"
        # domains: ""

    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      annotations:
        metallb.universe.tf/address-pool: dev-infra
      labels:
        app: chronograf 
      portName: http

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations: 
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdiPlayNetwork"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hostname: &uri chronograf.${SECRET_DEV_DOMAIN}

      tls: true
      secretName: *uri
      path: /

