---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 17.0.11
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    architecture: standalone
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 7.0.4-debian-11-r11
        
    ## Redis&reg; Authentication parameters
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/redis#setting-the-server-password-on-first-run
    auth:
      enabled: false
      ## @param auth.sentinel Enable password authentication on sentinels too
      sentinel: true
      existingSecret: ""
      ## @param auth.existingSecretPasswordKey Password key to be retrieved from existing secret
      ## NOTE: ignored unless `auth.existingSecret` parameter is set
      existingSecretPasswordKey: ""

    master:
      persistence:
        enabled: true
        existingClaim: redis-data-volume

      service:
        type: LoadBalancer
        loadBalancerIP: "${SVC_REDIS_ADDR}"
        annotations:
          metallb.universe.tf/address-pool: dev-infra

    replica:
      replicaCount: 2
      persistence:
        enabled: true
        storageClass: local-path
        size: 2Gi
