# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden
  namespace: default
spec:
  sourcePVC: vaultwarden-config-volume
  trigger:
    #schedule: "0 7 * * *"
    manual: manual-backup-0
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: vaultwarden
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: longhorn-snapshot-vsc
    storageClassName: longhorn
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 7
      within: 3d
