---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kopia
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    initContainers:
      wait-for-repo:
        image: ghcr.io/onedr0p/kopia:0.12.1@sha256:4ee9bc68299481fced34899eaec8bd42a6c9e5db902c6bef61ba0b0094b25b3b
        command:
          - /bin/bash
          - -c
          - |-
            until [ -f /snapshots/kopia.repository.f ]; do
                printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                sleep 1
            done
        volumeMounts:
          - name: snapshots
            mountPath: /snapshots
    image:
      repository: ghcr.io/onedr0p/kopia
      tag: 0.12.1@sha256:4ee9bc68299481fced34899eaec8bd42a6c9e5db902c6bef61ba0b0094b25b3b
      pullPolicy: Always
    env:
      TZ: "${TIMEZONE}"
      KOPIA_PASSWORD: "none"
    command: kopia
    args:
      - server
      - --insecure
      - --address
      - 0.0.0.0:80
      - --metrics-listen-addr
      - 0.0.0.0:8080
      - --without-password
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "backup-restore"
          hajimari.io/group: "Storage"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: *host
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: repository.config
        mountPath: /config/repository.config
        readOnly: true
      snapshots:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /volume1/backups/kopia-dev
        mountPath: /snapshots
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 250Mi
