apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:11.0.3-base-ubuntu20.04
    command: ["bash"]
    args: ["-c", "while true; do sleep 30; done"]
    resources:
      limits:
        nvidia.com/gpu: 1

