apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "nvidia/cuda:12.4.0-runtime-ubuntu20.04"
    command: ["/bin/sh", "-c"]
    args:
      - >
        while true;
        do
          echo "Running CUDA application...";
          sleep 1;
        done
    resources:
      limits:
        nvidia.com/gpu: 1

