---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nameOverride: *app
    provider: cloudflare

    extraArgs:
      - --cloudflare-proxied
      - --annotation-filter=external-dns.home.arpa/enabled in (true)

    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-creds
            key: email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-creds
            key: api-key

    policy: sync

    sources:
      - ingress

    domainFilters:
      - "${SECRET_DEV_DOMAIN}"

    txtPrefix: "k8s."
    txtOwnerId: "homelab"

    logLevel: info

    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    serviceMonitor:
      enabled: true

    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 100Mi

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
