---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - helm-release.yaml
configMapGenerator:
  - name: mariadb-lb-configmap
    files:
      - haproxy.cfg=./config/haproxy.cfg
configurations:
  - ./patches/kustomizeconfig.yaml
labels:
  - pairs:
      app.kubernetes.io/name: mariadb-lb
      app.kubernetes.io/instance: mariadb-lb
      app.kubernetes.io/part-of: mariadb
