apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - github.com/kubernetes-sigs/node-feature-discovery//deployment/base/nfd-crds?ref=v0.18.2
  - helm-release.yaml
