apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-collabora
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    image:
      repository: collabora/code
      tag: 23.05.10.1.1
    
    env:
      extra_params: --o:ssl.termination=true --o:ssl.enable=false
    
    autoscaling:
      enabled: true
      target:  # deploymentname
      minReplicas:  1
      maxReplicas:  3
      targetCPUUtilizationPercentage:  80
      targetMemoryUtilizationPercentage:  80
  
    service:
      main:
        ports:
          http:
            port: 9980
    
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
          hajimari.io/group: "Storage"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "collabora.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
