---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: &name nextcloud-config
    namespace: storage
    labels:
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 8Gi
