apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-nextcloud-wellknown1
  namespace: networking
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "https://(.*)/.well-known/(card|cal)dav"
    replacement: "https://$1/remote.php/dav/"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-nextcloud-wellknown2
  namespace: networking
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  redirectRegex:
    permanent: true
    regex: "^https?://([^/]*)/.well-known/(webfinger|nodeinfo)$"
    replacement: "https://$1/index.php/.well-known/$2"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-nextcloud-headers
  namespace: networking
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    accessControlMaxAge: 100
    hostsProxyHeaders:
      - "X-Forwarded-Host"
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
    forceSTSHeader: true
    # frameDeny: true #overwritten by customFrameOptionsValue
    #customFrameOptionsValue: "allow-from https:${SECRET_DEV_DOMAIN}" #CSP takes care of this but may be needed for organizr.
    customFrameOptionsValue: "SAMEORIGIN" #CSP takes care of this but may be needed for organizr.
    contentTypeNosniff: true
    browserXssFilter: true
    #referrerPolicy: "origin-when-cross-origin"
    referrerPolicy: "same-origin"
    # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
    # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
    # contentSecurityPolicy: "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
    permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
    customResponseHeaders:
      X-Robots-Tag: "none"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-nextcloud-headers
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-secure-headers
      - name: middlewares-rate-limit
      - name: middlewares-nextcloud-wellknown1
      - name: middlewares-nextcloud-wellknown2
      - name: middlewares-authelia
