apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nodered-config-volume
    labels:
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi 

