apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
commonLabels:
  app.kubernetes.io/name: &app node-red
  app.kubernetes.io/instance: *app
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: packagejson
    files:
      - ./config/package.json
  - name: settingsjs
    files:
      - ./config/settings.js
generatorOptions:
  disableNameSuffixHash: true
