---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole-ruri
  namespace: default
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`guac.${SECRET_DEV_DOMAIN}`) 
    kind: Rule
    services:
    - name: whoami
      port: 80
