apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname fasten
  namespace: home
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: *appname
                key: DB_HOST
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: *appname
                key: DB_NAME
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: *appname
                key: DB_NAME
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: *appname
                key: DB_PASSWORD
