---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app firefox
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/jlesage/firefox
      tag: v22.12.2
    env:
      TZ: "${TIMEZONE}"
      UMASK: 022
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
    service:
      main:
        ports:
          http:
            port: &port 5800
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "firefox"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
            ##cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "firefox.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
#    probes:
#      liveness: &probes
#        enabled: true
#        custom: true
#        spec:
#          httpGet:
#            path: /health
#            port: *port
#          initialDelaySeconds: 0
#          periodSeconds: 10
#          timeoutSeconds: 1
#          failureThreshold: 3
#      readiness: *probes
#      startup:
#        enabled: false
    persistence:
      config:
        enabled: true
#    resources:
#      requests:
#        cpu: 10m
#        memory: 50Mi
#      limits:
#        memory: 500Mi
