apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname changedetection
  namespace: utilities

spec:
  releaseName: *appname
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 4
  values:
    service:
      main:
        primary: true
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 5000
        type: LoadBalancer
        externalTrafficPolicy: Local

    image:
      repository: ghcr.io/dgtlmoon/changedetection.io
      tag: 0.42.2
      pullPolicy: Always
    
    env:
      TZ: ${TIMEZONE}
    
    persistence:
      data:
        enabled: true
        mountPath: /datastore
        existingClaim: changedetection-data-volume

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "swap-horizontal"
          hajimari.io/appName: "Change Detection"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "change.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *uri
            secretName: *uri

    nodeSelector:
      node-role.kubernetes.io/worker: "true"
