---
# yaml-language-server: $schema=http://kubernetes-schemas.local.lan:8080/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvidia-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.ngc.nvidia.com/nvidia
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvidia
  namespace: flux-system
spec:
  interval: 2h
  url: https://nvidia.github.io/k8s-device-plugin
---
