apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: utilities

spec:
  releaseName: *app
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 10m
  interval: 6m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
   
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        primary: true
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
        type: LoadBalancer
        externalTrafficPolicy: Local

    strategy:
      type: Recreate
    
    image:
      repository: vaultwarden/server
      tag: 1.34.3
    
    # -- environment variables.
    env:
      DATA_FOLDER: "config"
      TZ: ${TIMEZONE}
      SIGNUPS_ALLOWED : false
      WEBSOCKET_ENABLED : true

    envFrom:
      - secretRef:
          name: *app
    
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        existingClaim: "vaultwarden-config-volume"
    
    mariadb:
      enabled: false

    postgresql:
      enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          hajimari.io/group: "Utilities"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "vault.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
            - *uri
            secretName: *uri
      secondary:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-no-auth@kubernetescrd
        hosts:
          - host: &uri2 "vault.${SECRET_PROD_DOMAIN_MGO}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /admin
                pathType: Prefix
                service:
                  port: 1000
        tls:
          - hosts:
            - *uri2
            secretName: *uri2

    nodeSelector:
      node-role.kubernetes.io/worker: "true"
