---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: utilities
spec:
  interval: 5m
  chart:
    spec:
      chart: echo-server
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: ealenn-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/ealen/echo-server
      tag: 0.7.0
    ingress:
      enabled: false
    service:
      type: LoadBalancer
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
