apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities
commonLabels:
  app.kubernetes.io/name: &app ltb-project
  app.kubernetes.io/instance: *app
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: ltb-config
    files:
      - config.inc.local.php
  - name: custom-css
    files:
      - custom.css
  - name: poststart-sh 
    files:
      - postStart.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
