---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegraf-data-volume
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
