---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app nextcloud-redis
  app.kubernetes.io/instance: *app
resources:
  - redis.yaml
  - socks-pvc.yaml
  - configmap.yaml
