---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: nextcloud-redis
  namespace: storage
spec:
  #  auth:
  #    secretPath: nextcloud-config
  sentinel:
    replicas: 1
    image: redis:7.0.11
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 1
    image: redis:7.0.11
    imagePullPolicy: Always
    command:
      - "redis-server"
      - "/run/redis.conf"
    containerSecurityContext:
      runAsUser: 82
      runAsGroup: 82
    securityContext:
      runAsUser: 82
      runAsGroup: 82
      fsGroup: 82
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    extraVolumes:
    - name: socks-pvc
      persistentVolumeClaim:
        claimName: redis-socks-pvc
    - name: redis-configmap
      configMap:
        name: redis-config
    extraVolumeMounts:
    - name: socks-pvc
      mountPath: "/run/redis"
      readOnly: false
    - name: redis-configmap
      mountPath: "/run/redis.conf"
      subPath: "redis.conf"
