---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 12.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      existingSecret: mariadb-secret
      database: ""
      username: ""
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-data-volume
      service:
        type: LoadBalancer
        loadBalancerIP: ${SVC_MARIADB_PRIMARY_ADDR}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
