apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.20.0
  labels:
    cnpg.io/cluster: defaultpg
  name: defaultpg-ex
  namespace: databases
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: defaultpg
    role: primary
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.12.5
